FROM docker.io/library/ruby:3.4.7 AS jekyll

ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /usr/src/app && \
    mkdir -p /usr/src/app/node_modules && \  
    mkdir -p /usr/src/app/docker_data && \  
    mkdir -p /gems && \
    apt update && \
    apt install -yqq locales && \
    apt clean && rm -r /var/lib/apt/lists
WORKDIR /usr/src/app

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    dpkg-reconfigure locales && \
    /usr/sbin/update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

ENV BUNDLE_PATH="/gems"
COPY . /usr/src/app/
RUN bundle install
RUN bundle exec jekyll build

FROM docker.io/library/nginx:1.29-alpine

COPY --from=jekyll --chown=nginx:nginx /usr/src/app/_site /usr/share/nginx/html
COPY nginx-*.conf /etc/nginx/conf.d/
